apiVersion: v1
kind: Secret
metadata:
  name: exml-api-secrets
type: Opaque
stringData:
  api-keys: '{"admin-key":{"role":"admin","key_id":"k8s-admin"},"predict-key":{"role":"predictor","key_id":"k8s-predict"}}'
